-- ============================================================
-- BSC Retail CRM - MySQL DDL Schema
-- Run this inside Hostinger phpMyAdmin SQL tab
-- ============================================================

CREATE TABLE IF NOT EXISTS `Settings` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `companyName` VARCHAR(255) DEFAULT 'Retail CRM',
  `companyLogoUrl` VARCHAR(500) NULL,
  `operatingStart` VARCHAR(50) DEFAULT '10:00',
  `operatingEnd` VARCHAR(50) DEFAULT '22:00',
  `footfallGraceMin` INT DEFAULT 30,
  `footfallEditCutoff` VARCHAR(50) DEFAULT '10:30',
  `derEmail` VARCHAR(255) NULL,
  `derWhatsappNote` VARCHAR(500) NULL,
  `setupComplete` BOOLEAN DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `User` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('super_admin','admin','crm_manager','crm_staff','purchase_manager','telecaller','vm','pm','hr') NOT NULL,
  `sectionsAssigned` VARCHAR(255) DEFAULT 'ALL',
  `isActive` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `Section` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `sectionId` VARCHAR(50) UNIQUE NOT NULL,
  `sectionName` VARCHAR(255) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `managerName` VARCHAR(255) NULL,
  `managerEmail` VARCHAR(255) NULL,
  `isActive` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `FootfallEntry` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` VARCHAR(50) NOT NULL,
  `slotStart` INT NOT NULL,
  `slotEnd` INT NOT NULL,
  `count` INT NOT NULL,
  `remarks` VARCHAR(500) NULL,
  `submittedBy` VARCHAR(255) NOT NULL,
  `editedBy` VARCHAR(255) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  UNIQUE KEY `idx_date_slot` (`date`, `slotStart`)
);

CREATE TABLE IF NOT EXISTS `DailySummary` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` VARCHAR(50) UNIQUE NOT NULL,
  `billsCount` INT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `FeedbackQuestion` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `qId` VARCHAR(50) UNIQUE NOT NULL,
  `qText` TEXT NOT NULL,
  `options` JSON NOT NULL,
  `isMandatory` BOOLEAN DEFAULT TRUE,
  `displayOrder` INT DEFAULT 1,
  `isActive` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `Feedback` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` VARCHAR(50) NOT NULL,
  `source` VARCHAR(100) NOT NULL,
  `area` VARCHAR(255) NOT NULL,
  `yourVoice` TEXT NULL,
  `custName` VARCHAR(255) NULL,
  `custMobile` VARCHAR(50) NULL,
  `custDob` VARCHAR(50) NULL,
  `q0` VARCHAR(255) NULL, `q0_other` VARCHAR(255) NULL,
  `q1` VARCHAR(255) NULL, `q1_other` VARCHAR(255) NULL,
  `q2` VARCHAR(255) NULL, `q2_other` VARCHAR(255) NULL,
  `q3` VARCHAR(255) NULL, `q3_other` VARCHAR(255) NULL,
  `q4` VARCHAR(255) NULL, `q4_other` VARCHAR(255) NULL,
  `q5` VARCHAR(255) NULL, `q5_other` VARCHAR(255) NULL,
  `q6` VARCHAR(255) NULL, `q6_other` VARCHAR(255) NULL,
  `q7` VARCHAR(255) NULL, `q7_other` VARCHAR(255) NULL,
  `status` VARCHAR(50) DEFAULT 'new',
  `actionTaken` TEXT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `CallQueue` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `feedbackId` INT UNIQUE NOT NULL,
  `callType` VARCHAR(100) NOT NULL,
  `callStatus` VARCHAR(100) NULL,
  `callNote` TEXT NULL,
  `callAttempts` INT DEFAULT 0,
  `escalated` BOOLEAN DEFAULT FALSE,
  `followupDate` VARCHAR(50) NULL,
  `isDone` BOOLEAN DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`feedbackId`) REFERENCES `Feedback`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `DivertReason` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `reasonId` VARCHAR(50) UNIQUE NOT NULL,
  `reasonText` TEXT NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `Divert` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `divertId` VARCHAR(100) UNIQUE NOT NULL,
  `date` VARCHAR(50) NOT NULL,
  `sectionId` VARCHAR(50) NOT NULL,
  `sectionName` VARCHAR(255) NOT NULL,
  `productWanted` VARCHAR(255) NOT NULL,
  `qty` INT NULL,
  `priceRange` VARCHAR(255) NULL,
  `fabricOccasion` VARCHAR(255) NULL,
  `reasonCode` VARCHAR(50) NOT NULL,
  `detailedRemarks` TEXT NULL,
  `comingBack` VARCHAR(50) NOT NULL,
  `custName` VARCHAR(255) NULL,
  `custMobile` VARCHAR(50) NULL,
  `expectedDate` VARCHAR(50) NULL,
  `raisedBy` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) DEFAULT 'open',
  `pmAction` TEXT NULL,
  `adminRemark` TEXT NULL,
  `closedAt` DATETIME NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `DivertUpdate` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `divertId` INT NOT NULL,
  `updatedBy` VARCHAR(255) NOT NULL,
  `userId` INT NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `note` TEXT NOT NULL,
  `newStatus` VARCHAR(100) NULL,
  `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`divertId`) REFERENCES `Divert`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`userId`) REFERENCES `User`(`id`)
);

CREATE TABLE IF NOT EXISTS `CashSettlement` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` VARCHAR(50) UNIQUE NOT NULL,
  `saleAmount` DECIMAL(12,2) NOT NULL,
  `billsCount` INT NOT NULL,
  `abv` DECIMAL(12,2) NOT NULL,
  `cashTotal` DECIMAL(12,2) NOT NULL,
  `cardTotal` DECIMAL(12,2) NOT NULL,
  `upiTotal` DECIMAL(12,2) NOT NULL,
  `cashDiff` DECIMAL(12,2) NOT NULL,
  `cardDiff` DECIMAL(12,2) NOT NULL,
  `upiDiff` DECIMAL(12,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `CashCounterReport` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `settlementId` INT NOT NULL,
  `counterId` VARCHAR(50) NOT NULL,
  `cashierName` VARCHAR(255) NOT NULL,
  `cashDiff` DECIMAL(12,2) NOT NULL,
  `cardDiff` DECIMAL(12,2) NOT NULL,
  `upiDiff` DECIMAL(12,2) NOT NULL,
  `staffDisc` DECIMAL(12,2) NOT NULL,
  `custDisc` DECIMAL(12,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`settlementId`) REFERENCES `CashSettlement`(`id`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `VMUser` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) UNIQUE NOT NULL,
  `pin` VARCHAR(255) NOT NULL,
  `role` VARCHAR(100) NOT NULL,
  `isActive` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `VMChecklistPoint` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `pointNo` INT UNIQUE NOT NULL,
  `aspect` VARCHAR(255) NOT NULL,
  `point` TEXT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `frequency` VARCHAR(100) NOT NULL,
  `isActive` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `VMSubmission` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` VARCHAR(50) NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `floor` VARCHAR(255) NULL,
  `submittedBy` VARCHAR(255) NOT NULL,
  `score` DECIMAL(3,2) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS `VMSubmissionEntry` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `submissionId` INT NOT NULL,
  `pointNo` INT NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  `remarks` TEXT NULL,
  `photoLink` VARCHAR(500) NULL,
  `photoThumb` VARCHAR(500) NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  FOREIGN KEY (`submissionId`) REFERENCES `VMSubmission`(`id`) ON DELETE CASCADE
);
